### ISSUE TITLE
The RPC different from Okhttp Library or URLConection??

### ISSUE THREAD

**Issue by shenxiaolin** [sdklite/rpc-http#1]
The RPC different from Okhttp Library or URLConection??

**Comment by johnsonlee** [comment]
Yes, it's [RPC](https://github.com/sdklite/rpc) is an abstraction API layer, and [RPC-HTTP](https://github.com/sdklite/rpc-http) is an implementation of [RPC](https://github.com/sdklite/rpc) based on OkHttp, like [Retrofit](https://github.com/square/retrofit) but different.
